import { Link } from '@/i18n/navigation';
import { setRequestLocale } from 'next-intl/server';
import PublicNav from '@/components/public/public-nav';
import PublicFooter from '@/components/public/public-footer';

const VALUES = [
  { icon: '🎯', title: 'Functional by default', desc: 'Every feature you see is working — products, RFQs, chat, translation, logistics, wallet. No demo screens.' },
  { icon: '🛡️', title: 'Compliance first', desc: 'Role-based permissions, immutable audit logs and a transparent 2% commission model regulated by the platform ledger.' },
  { icon: '🌍', title: 'Ethiopian & Chinese at heart', desc: 'We bridge Addis Ababa and Guangzhou so SMEs on both sides can trade without middlemen or language walls.' },
  { icon: '🗣️', title: 'Language-inclusive', desc: 'English, Chinese (Simplified), Amharic and Afaan Oromo — with real translation, generated by the platform engine.' },
];

const MILESTONES = [
  { t: 'Platform foundation', d: 'Core tenant model, security, finance, CRM and product services designed around Ethiopian & Chinese trade scenarios.' },
  { t: 'Marketplace & negotiation', d: 'Multi-language product listings, RFQ hub, and the global negotiation room with auto-translation go live.' },
  { t: 'Logistics & pricing', d: 'Route estimation and Ethiopian customs/VAT landed-cost calculators give buyers total clarity before ordering.' },
  { t: 'Payments & trust', d: 'Wallet, subscriptions and audited platform fees complete the loop — every transaction traceable end-to-end.' },
];

export default async function AboutPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="pub-body">
      <PublicNav />

      <section className="pub-hero" style={{ paddingBottom: 40 }}>
        <span className="pub-hero-badge">About Us</span>
        <h1 className="pub-hero-title">
          The commercial bridge between <span className="grad">Ethiopia and China</span>
        </h1>
        <p className="pub-hero-sub">
          ETHIO-BRIDGE is built for the businesses doing real trade between two of the
          world&apos;s most dynamic markets — helping them find each other, trust each
          other, and close deals in their own languages.
        </p>
      </section>

      <section className="pub-section alt" style={{ paddingTop: 40 }}>
        <div className="pub-container">
          <div className="pub-split">
            <div>
              <span className="pub-kicker" style={{ textAlign: 'left' }}>Our mission</span>
              <h2 style={{ textAlign: 'left', fontSize: 26 }}>
                Remove every barrier between supplier and buyer
              </h2>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 14 }}>
                Ethiopian buyers import machinery, solar equipment, electronics and consumer
                goods from China; Ethiopian exporters sell coffee, textiles and agricultural
                products outward. Historically the journey is blocked by three walls —
                language, logistics cost visibility, and trust.
              </p>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 14 }}>
                ETHIO-BRIDGE tackles all three: live translation across four languages, a
                tariff and landed-cost calculator built on Ethiopian NBR schedules, and a
                permissioned, fully audited platform where every action is recorded.
              </p>
              <div className="flex" style={{ gap: 10, flexWrap: 'wrap' }}>
                <Link href="/services" className="btn btn-primary" style={{ borderRadius: '11px', padding: '11px 22px' }}>
                  Our services
                </Link>
                <Link href="/register" className="btn" style={{ borderRadius: '11px', padding: '11px 22px', background: 'var(--color-surface)', border: '1px solid var(--color-border)' }}>
                  Join the bridge
                </Link>
              </div>
            </div>
            <div className="pub-figure">🌉</div>
          </div>
        </div>
      </section>

      <section className="pub-section">
        <div className="pub-container">
          <span className="pub-kicker">What we stand for</span>
          <h2>Our values</h2>
          <p className="pub-section-desc">
            The principles behind every screen we ship.
          </p>
          <div className="pub-values">
            {VALUES.map((v) => (
              <div key={v.title} className="pub-value">
                <div className="pub-card-icon">{v.icon}</div>
                <h4>{v.title}</h4>
                <p>{v.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="pub-section alt">
        <div className="pub-container">
          <div className="pub-split" style={{ gridTemplateColumns: '0.9fr 1.1fr' }}>
            <div>
              <span className="pub-kicker" style={{ textAlign: 'left' }}>Our journey</span>
              <h2 style={{ textAlign: 'left', fontSize: 26 }}>Built step by step, always real</h2>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 4 }}>
                We ship working functionality and extend it — never mocked screens, never
                fake quotas. Here is how the platform has come together.
              </p>
            </div>
            <div>
              <div className="pub-timeline">
                {MILESTONES.map((m) => (
                  <div key={m.t} className="pub-tl-item">
                    <h4>{m.t}</h4>
                    <p>{m.d}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}